# -*- coding: utf-8 -*-
"""
@author: @mikegallimore
"""
PENALTIES = {'Abuse of officials': 'Abusive.Behavior',
                'Abuse of Officials': 'Abusive.Behavior',
                'Abusing officials': 'Abusive.Behavior', 
                'Abusing Officials': 'Abusive.Behavior',
                'Abusive': 'Abusive.Behavior',
                'Abusive language': 'Abusive.Behavior',
                'Abusive language-bench': 'Abusive.Behavior',
                'Abusive language-Bench': 'Abusive.Behavior',
                'Abusive Language-bench': 'Abusive.Behavior',
                'Abusive Language-Bench': 'Abusive.Behavior',
                'Abusive language - bench': 'Abusive.Behavior',
                'Abusive language - Bench': 'Abusive.Behavior',
                'Abusive Language - bench': 'Abusive.Behavior',
                'Abusive Language - Bench': 'Abusive.Behavior',
                'Abusive language - misconduct': 'Abusive.Behavior',
                'Abusive language - Misconduct': 'Abusive.Behavior',
                'Abusive Language - misconduct': 'Abusive.Behavior',
                'Abusive Language - Misconduct': 'Abusive.Behavior',
                'Aggressor': 'Instigator',
                'Bench': 'Bench.Infraction',
                'Broken': 'Broken.Stick',
                'Broken stick': 'Broken.Stick',
                'Broken Stick': 'Broken.Stick',
                'Broken-stick': 'Broken.Stick',
                'Broken-Stick': 'Broken.Stick',
                'Butt': 'Butt.Ending',
                'Butt-ending': 'Butt.Ending',
                'Butt-Ending': 'Butt.Ending',
                'Butt ending': 'Butt.Ending',
                'Butt Ending': 'Butt.Ending',
                'Checking': 'Checking.Behind',
                'Checking from behind': 'Checking.Behind',
                'Checking from Behind': 'Checking.Behind',
                'Closing': 'Delay.Game',
                'Closing hand on puck': 'Delay.Game',
                'Closing hand on Puck': 'Delay.Game',
                'Closing Hand on puck': 'Delay.Game',
                'Closing Hand on Puck': 'Delay.Game',
                'Closing hand over puck': 'Delay.Game',
                'Closing hand over Puck': 'Delay.Game',
                'Closing Hand over puck': 'Delay.Game',
                'Closing Hand over Puck': 'Delay.Game',
                'Coach or manager on the ice': 'Bench.Infraction',
                'Coach or Manager on the ice': 'Bench.Infraction',
                'Coach or Manager on the Ice': 'Bench.Infraction',
                'Concealing': 'Delay.Game',
                'Concealing puck': 'Delay.Game',
                'Concealing Puck': 'Delay.Game',
                'Concealing the puck': 'Delay.Game',
                'Concealing the Puck': 'Delay.Game',
                'Cross': 'Cross.Checking',
                'Cross check': 'Cross.Checking',
                'Cross Check': 'Cross.Checking',
                'Cross check - minor': 'Cross.Checking',
                'Cross check - Minor': 'Cross.Checking',              
                'Cross Check - Minor': 'Cross.Checking',
                'Cross check - double minor': 'Cross.Checking',
                'Cross check - Double Minor': 'Cross.Checking',                    
                'Cross Check - Double Minor': 'Cross.Checking',
                'Cross check - major': 'Cross.Checking',
                'Cross check - Major': 'Cross.Checking',                    
                'Cross Check - Major': 'Cross.Checking',
                'Cross checking': 'Cross.Checking',
                'Cross Checking': 'Cross.Checking',
                'Cross checking - minor': 'Cross.Checking',
                'Cross checking - Minor': 'Cross.Checking',           
                'Cross Checking - Minor': 'Cross.Checking',
                'Cross checking - double minor': 'Cross.Checking',
                'Cross checking - Double Minor': 'Cross.Checking',                
                'Cross Checking - Double Minor': 'Cross.Checking',
                'Cross checking - major': 'Cross.Checking',
                'Cross checking - Major': 'Cross.Checking',               
                'Cross Checking - Major': 'Cross.Checking',
                'Cross-checking': 'Cross.Checking',
                'Cross-Checking': 'Cross.Checking',
                'Cross-checking - minor': 'Cross.Checking',
                'Cross-checking - Minor': 'Cross.Checking',
                'Cross-Checking - Minor': 'Cross.Checking',
                'Cross-checking - double minor': 'Cross.Checking',
                'Cross-checking - Double Minor': 'Cross.Checking',
                'Cross-Checking - Double Minor': 'Cross.Checking',
                'Cross-checking - major': 'Cross.Checking',
                'Cross-checking - Major': 'Cross.Checking',
                'Cross-Checking - Major': 'Cross.Checking',
                'Delay': 'Delay.Game',
                'Delay gm': 'Delay.Game',
                'Delay Gm': 'Delay.Game',
                'Delay GM': 'Delay.Game',
                'Delay gm-faceoff violation': 'Delay.Game',
                'Delay gm-Faceoff violation': 'Delay.Game',
                'Delay gm-Faceoff Violation': 'Delay.Game',
                'Delay gm-face-off violation': 'Delay.Game',
                'Delay gm-Face-off violation': 'Delay.Game',
                'Delay gm-Face-off Violation': 'Delay.Game',
                'Delay gm - faceoff violation': 'Delay.Game',
                'Delay gm - Faceoff violation': 'Delay.Game',
                'Delay gm - Faceoff Violation': 'Delay.Game',
                'Delay gm - face-off violation': 'Delay.Game',
                'Delay gm - Face-off violation': 'Delay.Game',
                'Delay gm - Face-off Violation': 'Delay.Game',
                'Delay Gm-faceoff violation': 'Delay.Game',
                'Delay Gm-Faceoff violation': 'Delay.Game',
                'Delay Gm-Faceoff Violation': 'Delay.Game',
                'Delay Gm-face-off violation': 'Delay.Game',
                'Delay Gm-Face-off violation': 'Delay.Game',
                'Delay Gm-Face-off Violation': 'Delay.Game',
                'Delay Gm - faceoff violation': 'Delay.Game',
                'Delay Gm - Faceoff violation': 'Delay.Game',
                'Delay Gm - Faceoff Violation': 'Delay.Game',
                'Delay Gm - face-off violation': 'Delay.Game',
                'Delay Gm - Face-off violation': 'Delay.Game',
                'Delay Gm - Face-off Violation': 'Delay.Game',
                'Delay of game-faceoff violation': 'Delay.Game',
                'Delay of game-Faceoff violation': 'Delay.Game',
                'Delay of Game-Faceoff violation': 'Delay.Game',
                'Delay of Game-Faceoff Violation': 'Delay.Game',
                'Delay of game - faceoff violation': 'Delay.Game',
                'Delay of game - Faceoff violation': 'Delay.Game',
                'Delay of Game - Faceoff violation': 'Delay.Game',
                'Delay of Game - Faceoff Violation': 'Delay.Game',
                'Delay of game-face-off violation': 'Delay.Game',
                'Delay of game-Face-off violation': 'Delay.Game',
                'Delay of Game-Face-off violation': 'Delay.Game',
                'Delay of Game-Face-off Violation': 'Delay.Game',
                'Delay of game - face-off violation': 'Delay.Game',
                'Delay of game - Face-off violation': 'Delay.Game',
                'Delay of Game - Face-off violation': 'Delay.Game',
                'Delay of Game - Face-off Violation': 'Delay.Game',
                'Delay of game-ill. play goalie': 'Delay.Game',
                'Delay of game-Ill. play goalie': 'Delay.Game',
                'Delay of Game-Ill. play goalie': 'Delay.Game',
                'Delay of Game-Ill. Play Goalie': 'Delay.Game',
                'Delay of game-ill. play by goalie': 'Delay.Game',
                'Delay of game-Ill. play by goalie': 'Delay.Game',
                'Delay of Game-Ill. play by goalie': 'Delay.Game',
                'Delay of Game-Ill. Play by Goalie': 'Delay.Game',
                'Delay of game - ill. play goalie': 'Delay.Game',
                'Delay of game - Ill. play goalie': 'Delay.Game',
                'Delay of Game - Ill. play goalie': 'Delay.Game',
                'Delay of Game - Ill. Play Goalie': 'Delay.Game',
                'Delay of game - ill. play by goalie': 'Delay.Game',
                'Delay of game - Ill. play by goalie': 'Delay.Game',
                'Delay of Game - Ill. play by goalie': 'Delay.Game',
                'Delay of Game - Ill. Play by Goalie': 'Delay.Game',
                'Delay of game': 'Delay.Game',
                'Delay of Game': 'Delay.Game',
                'Delaying': 'Delay.Game',
                'Delaying game': 'Delay.Game',
                'Delaying Game': 'Delay.Game',
                'Delaying game-ill. play goalie': 'Delay.Game',
                'Delaying game-Ill. play goalie': 'Delay.Game',
                'Delaying Game-Ill. play goalie': 'Delay.Game',
                'Delaying Game-Ill. Play Goalie': 'Delay.Game',
                'Delaying game-ill. play by goalie': 'Delay.Game',
                'Delaying game-Ill. play by goalie': 'Delay.Game',
                'Delaying Game-Ill. play by goalie': 'Delay.Game',
                'Delaying Game-Ill. Play by Goalie': 'Delay.Game',
                'Delaying game - ill. play goalie': 'Delay.Game',
                'Delaying game - Ill. play goalie': 'Delay.Game',
                'Delaying Game - Ill. play goalie': 'Delay.Game',
                'Delaying Game - Ill. Play Goalie': 'Delay.Game',
                'Delaying game - illegal play by goalie': 'Delay.Game',
                'Delaying game - Illegal play by goalie': 'Delay.Game',
                'Delaying Game - Illegal play by goalie': 'Delay.Game',
                'Delaying Game - Illegal Play by Goalie': 'Delay.Game',
                'Delay of game-puck over glass': 'Delay.Game',
                'Delay of game-Puck over glass': 'Delay.Game',
                'Delay of Game-Puck over glass': 'Delay.Game',
                'Delay of Game-Puck Over Glass': 'Delay.Game',
                'Delay of game - puck over glass': 'Delay.Game',
                'Delay of game - Puck over glass': 'Delay.Game',
                'Delay of Game - Puck over glass': 'Delay.Game',
                'Delay of Game - Puck Over Glass': 'Delay.Game',
                'Delaying game-puck over glass': 'Delay.Game',
                'Delaying game-Puck over glass': 'Delay.Game',
                'Delaying Game-Puck over glass': 'Delay.Game',
                'Delaying Game-Puck Over Glass': 'Delay.Game',
                'Delaying game - puck over glass': 'Delay.Game',
                'Delaying game - Puck over glass': 'Delay.Game',
                'Delaying Game - Puck over glass': 'Delay.Game',
                'Delaying Game - Puck Over Glass': 'Delay.Game',
                'Delay of game-smothering puck': 'Delay.Game',
                'Delay of game-Smothering puck': 'Delay.Game',
                'Delay of Game-Smothering puck': 'Delay.Game',
                'Delay of Game-Smothering Puck': 'Delay.Game',
                'Delay of game - smothering puck': 'Delay.Game',
                'Delay of game - Smothering puck': 'Delay.Game',
                'Delay of Game - Smothering puck': 'Delay.Game',
                'Delay of Game - Smothering Puck': 'Delay.Game',
                'Delaying game-smothering Puck': 'Delay.Game',             
                'Delaying game-Smothering puck': 'Delay.Game',
                'Delaying Game-Smothering puck': 'Delay.Game',   
                'Delaying Game-Smothering Puck': 'Delay.Game',
                'Delaying game - smothering Puck': 'Delay.Game',             
                'Delaying game - Smothering puck': 'Delay.Game',   
                'Delaying Game - Smothering puck': 'Delay.Game', 
                'Delaying Game - Smothering Puck': 'Delay.Game',
                'Delaying the game': 'Delay.Game',  
                'Delaying the Game': 'Delay.Game',   
                'Face': 'Delay.Game',
                'Face-off': 'Delay.Game',
                'Face-Off': 'Delay.Game',
                'Face-off violatoin': 'Delay.Game',
                'Face-Off Violation': 'Delay.Game',
                'Faceoff': 'Delay.Game',
                'Face-off violation': 'Delay.Game',
                'Face-off Violation': 'Delay.Game',
                'Faceoff violation': 'Delay.Game',
                'Faceoff Violation': 'Delay.Game',   
                'Game': 'Game.Misconduct',
                'Game misconduct': 'Game.Misconduct',
                'Game Misconduct': 'Game.Misconduct',
                'Goalie interference': 'Interference',
                'Goalie Interference': 'Interference',
                'Goaltender interference': 'Interference',
                'Goaltender Interference': 'Interference',
                'Goalie leave crease': 'Delay.Game',
                'Goalie Leave Crease': 'Delay.Game',
                'Head': 'Head.Butting',
                'Head butting': 'Head.Butting',
                'Head Butting': 'Head.Butting',
                'Head-butting': 'Head.Butting',
                'Head-Butting': 'Head.Butting',
                'Head butting-double minor': 'Head.Butting',
                'Head butting- Double minor': 'Head.Butting',
                'Head Butting-double minor': 'Head.Butting',
                'Head Butting-Double minor': 'Head.Butting',
                'Head butting-Double Minor': 'Head.Butting',
                'Head butting - double minor': 'Head.Butting',
                'Head butting - Double minor': 'Head.Butting',
                'Head Butting - double minor': 'Head.Butting',
                'Head Butting - Double minor': 'Head.Butting',
                'Head butting - Double Minor': 'Head.Butting',
                'Head-butting-double minor': 'Head.Butting',
                'Head-butting- Double minor': 'Head.Butting',
                'Head-Butting-double minor': 'Head.Butting',
                'Head-Butting-Double minor': 'Head.Butting',
                'Head-butting-Double Minor': 'Head.Butting',
                'Head-butting - double minor': 'Head.Butting',
                'Head-butting - Double minor': 'Head.Butting',
                'Head-Butting - double minor': 'Head.Butting',
                'Head-Butting - Double minor': 'Head.Butting',
                'Head-butting - Double Minor': 'Head.Butting',
                'Hi': 'High.Sticking',
                'Hi stick': 'High.Sticking',
                'Hi Stick': 'High.Sticking',
                'Hi stick - double minor': 'High.Sticking',
                'Hi Stick - Double Minor': 'High.Sticking',
                'Hi stick - major': 'High.Sticking',
                'Hi Stick - Major': 'High.Sticking',
                'Hi stick - minor': 'High.Sticking',
                'Hi Stick - Minor': 'High.Sticking',
                'Hi sticking': 'High.Sticking',
                'Hi Sticking': 'High.Sticking',
                'Hi sticking - double minor': 'High.Sticking',
                'Hi Sticking - Double Minor': 'High.Sticking',
                'Hi sticking - major': 'High.Sticking',
                'Hi Sticking - Major': 'High.Sticking',
                'Hi sticking - minor': 'High.Sticking',
                'Hi Sticking - Minor': 'High.Sticking',
                'Hi-sticking': 'High.Sticking',
                'Hi-Sticking': 'High.Sticking',
                'Hi-sticking - double minor': 'High.Sticking',
                'Hi-Sticking - Double Minor': 'High.Sticking',
                'Hi-sticking - major': 'High.Sticking',
                'Hi-Sticking - Major': 'High.Sticking',
                'Hi-sticking - minor': 'High.Sticking',
                'Hi-Sticking - Minor': 'High.Sticking',
                'High': 'High.Sticking',
                'High stick': 'High.Sticking',
                'High Stick': 'High.Sticking',
                'High stick - double minor': 'High.Sticking',
                'High Stick - Double Minor': 'High.Sticking',
                'High stick - major': 'High.Sticking',
                'High Stick - Major': 'High.Sticking',
                'High stick - minor': 'High.Sticking',
                'High Stick - Minor': 'High.Sticking',
                'High sticking': 'High.Sticking',
                'High Sticking': 'High.Sticking',
                'High sticking - double minor': 'High.Sticking',
                'High Sticking - Double Minor': 'High.Sticking',
                'High sticking - major': 'High.Sticking',
                'High Sticking - Major': 'High.Sticking',
                'High sticking - minor': 'High.Sticking',
                'High Sticking - Minor': 'High.Sticking',
                'High-sticking': 'High.Sticking',
                'High-Sticking': 'High.Sticking',
                'High-sticking - double minor': 'High.Sticking', 
                'High-Sticking - Double Minor': 'High.Sticking',
                'High-sticking - major': 'High.Sticking',
                'High-Sticking - Major': 'High.Sticking',
                'High-sticking - minor': 'High.Sticking',
                'High-Sticking - Minor': 'High.Sticking',
                'Holding the stick': 'Holding',
                'Holding the Stick': 'Holding',
                'Illegal': 'Illegal.Action',
                'Illegal check to head': 'Check.Head',
                'Illegal Check to Head': 'Check.Head',
                'Illegal equipment': 'Illegal.Equipment',
                'Illegal Equipment': 'Illegal.Equipment',
                'Illegal stick': 'Illegal.Equipment',           
                'Illegal Stick': 'Illegal.Equipment',
                'Illegal substitution': 'Bench.Infraction',
                'Illegal Substitution': 'Bench.Infraction',
                'Instigator-face shield': 'Instigator',
                'Instigator-Face shield': 'Instigator',
                'Instigator-Face Shield': 'Instigator',
                'Instigator - face shield': 'Instigator',
                'Instigator - Face shield': 'Instigator',
                'Instigator - Face Shield': 'Instigator',
                'Interference - goalie': 'Interference',
                'Interference - Goalie': 'Interference',
                'Interference - goalkeeper': 'Interference',
                'Interference - Goalkeeper': 'Interference',
                'Interference - goaltender': 'Interference',
                'Interference - Goaltender': 'Interference' ,     
                'Interference on Goaltender': 'Interference',
                'Interfering with the goalie': 'Interference',
                'Interfering with the Goalie': 'Interference',
                'Interfering with the Goalkeeper': 'Interference',
                'Interfering with the Goalkeeper': 'Interference',
                'Interfering with the Goaltender': 'Interference',
                'Interfering with the Goaltender': 'Interference',
                'Leaving': 'Bench.Infraction',
                'Leaving bench-bench': 'Bench.Infraction',
                'Leaving bench-Bench': 'Bench.Infraction',
                'Leaving Bench-Bench': 'Bench.Infraction',
                'Leaving bench - bench': 'Bench.Infraction',
                'Leaving bench - Bench': 'Bench.Infraction',
                'Leaving Bench - Bench': 'Bench.Infraction',
                'Leaving penalty box': 'Bench.Infraction',
                'Leaving Penalty Box': 'Bench.Infraction',
                'Leaving penalty box-bench': 'Bench.Infraction',
                'Leaving penalty box-Bench': 'Bench.Infraction',
                'Leaving Penalty Box-Bench': 'Bench.Infraction',
                'Leaving penalty box - bench': 'Bench.Infraction',
                'Leaving penalty box - Bench': 'Bench.Infraction',
                'Leaving Penalty Box - Bench': 'Bench.Infraction',
                'Match penalty': 'Match.Penalty',
                'Match Penalty': 'Match.Penalty',
                'Objects': 'Bench.Infraction',
                'Objects on ice': 'Bench.Infraction',                
                'Objects on Ice': 'Bench.Infraction',
                'Objects on ice-bench': 'Bench.Infraction',
                'Objects on ice-Bench': 'Bench.Infraction',
                'Objects on Ice-Bench': 'Bench.Infraction',
                'Objects on ice - bench': 'Bench.Infraction',
                'Objects on ice - Bench': 'Bench.Infraction',
                'Objects on Ice - Bench': 'Bench.Infraction',
                'Player': 'Bench.Infraction',
                'Player leaves bench': 'Bench.Infraction',
                'Player leaves Bench': 'Bench.Infraction',
                'Player leaves bench-bench': 'Bench.Infraction',
                'Player leaves bench-Bench': 'Bench.Infraction',
                'Player Leaves Bench-Bench': 'Bench.Infraction',
                'Player leaves bench - bench': 'Bench.Infraction',
                'Player leaves bench - Bench': 'Bench.Infraction',
                'Player Leaves Bench - Bench': 'Bench.Infraction',
                'PS': 'Penalty.Shot',
                'PS-covering puck in crease': 'Delay.Game',
                'PS-Covering puck in crease': 'Delay.Game',
                'PS-Covering Puck in Crease': 'Delay.Game',
                'PS - covering puck in crease': 'Delay.Game',
                'PS - Covering puck in crease': 'Delay.Game',
                'PS - Covering Puck in Crease': 'Delay.Game',
                'PS-Goalie displaced net': 'Delay.Game',
                'PS - Goalie displaced net': 'Delay.Game',
                'PS-Goalkeeper displaced net': 'Delay.Game',
                'PS - Goalkeeper displaced net': 'Delay.Game',
                'PS-Goaltender displaced net': 'Delay.Game',
                'PS - Goaltender displaced net': 'Delay.Game',
                'PS-holding on breakway': 'Holding',
                'PS-Holding on breakway': 'Holding',
                'PS-Holding on Breakway': 'Holding',
                'PS - holding on breakaway': 'Holding',
                'PS - Holding on breakaway': 'Holding',
                'PS - Holding on Breakaway': 'Holding',
                'PS-holding stick on breakaway': 'Holding',
                'PS-Holding stick on breakaway': 'Holding',
                'PS-Holding Stick on Breakaway': 'Holding',
                'PS - holding stick on breakaway': 'Holding',
                'PS - Holding stick on breakaway': 'Holding',
                'PS - Holding Stick on Breakaway': 'Holding',
                'PS-hooking on breakaway': 'Hooking',
                'PS-Hooking on breakaway': 'Hooking',
                'PS-Hooking on Breakaway': 'Hooking',
                'PS - hooking on breakaway': 'Hooking',
                'PS - Hooking on breakaway': 'Hooking',
                'PS - Hooking on Breakaway': 'Hooking',
                'PS-net displaced': 'Delay.Game',
                'PS-Net displaced': 'Delay.Game',
                'PS-Net Displaced': 'Delay.Game',
                'PS - net displaced': 'Delay.Game',
                'PS - Net displaced': 'Delay.Game',
                'PS - Net Displaced': 'Delay.Game',
                'PS-picking up puck in crease': 'Delay.Game',
                'PS-Picking up puck in crease': 'Delay.Game',
                'PS-Picking up Puck in Crease': 'Delay.Game',
                'PS - picking up puck in crease': 'Delay.Game',
                'PS - Picking up puck in crease': 'Delay.Game',
                'PS - Picking up Puck in Crease': 'Delay.Game',
                'PS-thow object at puck': 'Throwing.Object',
                'PS-Thow object at puck': 'Throwing.Object',
                'PS-Thow Object at Puck': 'Throwing.Object',
                'PS-throw object at puck': 'Throwing.Object',
                'PS-Throw object at puck': 'Throwing.Object',
                'PS-Throw Object at Puck': 'Throwing.Object',
                'PS - thow object at puck': 'Throwing.Object',
                'PS - Thow object at puck': 'Throwing.Object',
                'PS - Thow Object at Puck': 'Throwing.Object',
                'PS - throw object at puck': 'Throwing.Object',
                'PS - Throw object at puck': 'Throwing.Object',
                'PS - Throw Object at Puck': 'Throwing.Object',
                'PS-tripping on breakaway': 'Tripping',
                'PS-Tripping on breakaway': 'Tripping',
                'PS-Tripping on Breakaway': 'Tripping',
                'PS - tripping on breakaway': 'Tripping',
                'PS - Tripping on breakaway': 'Tripping',
                'PS - Tripping on Breakaway': 'Tripping',
                'PS-slash on breakaway': 'Slashing',
                'PS-Slash on breakaway': 'Slashing',
                'PS-Slash on Breakaway': 'Slashing',
                'PS - slash on breakaway': 'Slashing',
                'PS - Slash on breakaway': 'Slashing',
                'PS - Slash on Breakaway': 'Slashing',
                'Puck': 'Delay.Game',
                'Spearing - double minor': 'Spearing',
                'Spearing - Double minor': 'Spearing',
                'Throwing stick': 'Throwing.Stick',
                'Throwing Stick': 'Throwing.Stick',
                'Too': 'Bench.Infraction',
                'Too many men': 'Bench.Infraction',
                'Too Many Men': 'Bench.Infraction',
                'Too many men/ice - bench': 'Bench.Infraction',
                'Too many men-bench': 'Bench.Infraction',
                'Too many men-Bench': 'Bench.Infraction',
                'Too Many Men-Bench': 'Bench.Infraction',
                'Too many men - bench': 'Bench.Infraction',
                'Too many men - Bench': 'Bench.Infraction',
                'Too Many Men - Bench': 'Bench.Infraction',
                'Too many men on the ice': 'Bench.Infraction',
                'Too Many Men on the Ice': 'Bench.Infraction',
                'Unsportsmanlike': 'Unsportsmanlike.Conduct',
                'Unsportsmanlike conduct': 'Unsportsmanlike.Conduct',
                'Unsportsmanlike Conduct': 'Unsportsmanlike.Conduct'}