# -*- coding: utf-8 -*-
"""
@author: @mikegallimore
"""
NHL = {'ANAHEIM DUCKS': 'ANA',
					'ARIZONA COYOTES': 'ARI',
					'ATLANTA THRASHERS': 'ATL',
					'BOSTON BRUINS': 'BOS',
					'BUFFALO SABRES': 'BUF',
					'CALGARY FLAMES': 'CGY',
					'CAROLINA HURRICANES': 'CAR',
					'CHICAGO BLACKHAWKS': 'CHI',
					'COLORADO AVALANCHE': 'COL',
					'COLUMBUS BLUE JACKETS': 'CBJ',
					'DALLAS STARS': 'DAL',
					'DETROIT RED WINGS': 'DET',
					'EDMONTON OILERS': 'EDM',
					'FLORIDA PANTHERS': 'FLA',
					'LOS ANGELES KINGS': 'LAK',
					'MINNESOTA WILD': 'MIN',
					'CANADIENS MONTREAL': 'MTL',
					'CANADIENS MONTRÉAL': 'MTL',
					'MONTRÉAL CANADIENS': 'MTL',
					'MONTREAL CANADIENS': 'MTL',
					'NASHVILLE PREDATORS': 'NSH',
					'NEW JERSEY DEVILS': 'NJD',
					'NEW YORK RANGERS': 'NYR',
					'NEW YORK ISLANDERS': 'NYI',
					'OTTAWA SENATORS': 'OTT',
					'PHILADELPHIA FLYERS': 'PHI',
					'PHOENIX COYOTES': 'PHX',
					'PITTSBURGH PENGUINS': 'PIT',
					'SAN JOSE SHARKS': 'SJS',
					'ST. LOUIS BLUES': 'STL',
					'TAMPA BAY LIGHTNING': 'TBL',
					'TORONTO MAPLE LEAFS': 'TOR',
					'VANCOUVER CANUCKS': 'VAN',
					'VEGAS GOLDEN KNIGHTS': 'VGK',
					'WASHINGTON CAPITALS': 'WSH',
					'WINNIPEG JETS': 'WPG'}

MONIKERS_DICT = {'Ducks': 'ANA', 
					'Coyotes': 'ARI', 
					'Thrashers': 'ATL', 
					'Bruins': 'BOS', 
					'Sabres': 'BUF', 
					'Flames': 'CGY', 
					'Hurricanes': 'CAR', 
					'Blackhawks': 'CHI', 
					'Avalanche': 'COL', 
					'Blue Jackets': 'CBJ', 
					'Stars': 'DAL', 
					'Red Wings': 'DET', 
					'Oilers': 'EDM', 
					'Panthers': 'FLA', 
					'Kings': 'LAK', 
					'Wild': 'MIN', 
					'Canadiens': 'MTL',
					'Predators': 'NSH', 
					'Devils': 'NJD', 
					'Rangers': 'NYR', 
					'Islanders': 'NYI', 
					'Senators': 'OTT', 
					'Flyers': 'PHI', 
					'Penguins': 'PIT', 
					'Sharks': 'SJS', 
					'Blues': 'STL', 
					'Lightning': 'TBL', 
					'Maple Leafs': 'TOR', 
					'Canucks': 'VAN', 
					'Golden Knights': 'VGK', 
					'Capitals': 'WSH',  
					'Jets': 'WPG'}

MONIKERS_DICT_PHX = {'Ducks': 'ANA', 
					'Coyotes': 'PHX', 
					'Thrashers': 'ATL', 
					'Bruins': 'BOS', 
					'Sabres': 'BUF', 
					'Flames': 'CGY', 
					'Hurricanes': 'CAR', 
					'Blackhawks': 'CHI', 
					'Avalanche': 'COL', 
					'Blue Jackets': 'CBJ', 
					'Stars': 'DAL', 
					'Red Wings': 'DET', 
					'Oilers': 'EDM', 
					'Panthers': 'FLA', 
					'Kings': 'LAK', 
					'Wild': 'MIN', 
					'Canadiens': 'MTL',
					'Predators': 'NSH', 
					'Devils': 'NJD', 
					'Rangers': 'NYR', 
					'Islanders': 'NYI', 
					'Senators': 'OTT', 
					'Flyers': 'PHI', 
					'Penguins': 'PIT', 
					'Sharks': 'SJS', 
					'Blues': 'STL', 
					'Lightning': 'TBL', 
					'Maple Leafs': 'TOR', 
					'Canucks': 'VAN', 
					'Golden Knights': 'VGK', 
					'Capitals': 'WSH',  
					'Jets': 'WPG'}

MONIKERS_DICT_WPG2ATL = {'Ducks': 'ANA', 
					'Coyotes': 'PHX', 
					'Thrashers': 'ATL', 
					'Bruins': 'BOS', 
					'Sabres': 'BUF', 
					'Flames': 'CGY', 
					'Hurricanes': 'CAR', 
					'Blackhawks': 'CHI', 
					'Avalanche': 'COL', 
					'Blue Jackets': 'CBJ', 
					'Stars': 'DAL', 
					'Red Wings': 'DET', 
					'Oilers': 'EDM', 
					'Panthers': 'FLA', 
					'Kings': 'LAK', 
					'Wild': 'MIN', 
					'Canadiens': 'MTL',
					'Predators': 'NSH', 
					'Devils': 'NJD', 
					'Rangers': 'NYR', 
					'Islanders': 'NYI', 
					'Senators': 'OTT', 
					'Flyers': 'PHI', 
					'Penguins': 'PIT', 
					'Sharks': 'SJS', 
					'Blues': 'STL', 
					'Lightning': 'TBL', 
					'Maple Leafs': 'TOR', 
					'Canucks': 'VAN', 
					'Golden Knights': 'VGK', 
					'Capitals': 'WSH',  
					'Jets': 'ATL'}

TRICODES = {'BUF': 'BUF',
				'L.A': 'LAK', 
				'N.J': 'NJD',
				'S.J': 'SJS',
				'T.B': 'TBL'}