# -*- coding: utf-8 -*-
"""
@author: @mikegallimore
"""
import argparse

parser = argparse.ArgumentParser()

# creates arguments to make use of in functions
parser.add_argument('season_id', help='Set the season (e.g. 20182019)')
parser.add_argument('game_id', help='Set the game (e.g. 20001)')

parser.add_argument('--teams', dest='teams', help='Set to skip to bypass running all scripts for teams', required=False)
parser.add_argument('--players', dest='players', help='Set to skip to bypass running all scripts for players', required=False)
parser.add_argument('--units', dest='units', help='Set to skip to bypass running all scripts for units', required=False)

parser.add_argument('--scope', dest='scope', help='Set to full to run additional scripts for teams, players and units', required=False)

parser.add_argument('--tweet', dest='tweet', help='Set to no to bypass sending autogenerated tweets', required=False)

args = parser.parse_args()


###
### Teams
###
    
if args.teams != 'skip' and args.tweet != 'no':
    import tweet_teams_gameflow
    tweet_teams_gameflow.parse_ids(args.season_id, args.game_id)
    tweet_teams_gameflow
   
    import tweet_teams_shotmaps
    tweet_teams_shotmaps.parse_ids(args.season_id, args.game_id)  
    tweet_teams_shotmaps

    import tweet_teams_summary
    tweet_teams_summary.parse_ids(args.season_id, args.game_id)
    tweet_teams_summary
   

###
### Players
###
    
if args.players != 'skip' and args.tweet != 'no': 
    import tweet_players_gamescore
    tweet_players_gamescore.parse_ids(args.season_id, args.game_id)
    tweet_players_gamescore

    import tweet_players_individual
    tweet_players_individual.parse_ids(args.season_id, args.game_id)
    tweet_players_individual
  
    import tweet_players_onice
    tweet_players_onice.parse_ids(args.season_id, args.game_id)
    tweet_players_onice

    
###
### Units
###
    

if args.units != 'skip' and args.tweet != 'no': 
    import tweet_units_onice
    tweet_units_onice.parse_ids(args.season_id, args.game_id)
    tweet_units_onice


if args.units != 'skip' and args.scope == 'full' and args.tweet != 'no':
    import tweet_units_lines_matchups_lines
    tweet_units_lines_matchups_lines.parse_ids(args.season_id, args.game_id)
    tweet_units_lines_matchups_lines
    
    import tweet_units_lines_matchups_pairings
    tweet_units_lines_matchups_pairings.parse_ids(args.season_id, args.game_id)
    tweet_units_lines_matchups_pairings
    
    import tweet_units_lines_teammates_pairings
    tweet_units_lines_teammates_pairings.parse_ids(args.season_id, args.game_id)
    tweet_units_lines_teammates_pairings