# -*- coding: utf-8 -*-
"""
@author: @mikegallimore
"""
APP_KEY = "YOUR_APP_KEY_HERE"
APP_SECRET = "YOUR_APP_SECRET_HERE"
OAUTH_TOKEN = "YOUR_OAUTH_TOKEN_HERE"
OAUTH_TOKEN_SECRET = "YOUR_OAUTH_TOKEN_SECRET_HERE"